# Generated by Django 5.2.6 on 2025-12-09 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('style_category', models.CharField(choices=[('luxury', 'Luxury'), ('streetwear', 'Streetwear'), ('fast_fashion', 'Fast Fashion'), ('sustainable', 'Sustainable'), ('avant_garde', 'Avant-Garde'), ('minimalist', 'Minimalist')], max_length=50)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('SS', 'Spring/Summer'), ('FW', 'Fall/Winter'), ('Resort', 'Resort'), ('Pre-Fall', 'Pre-Fall')], max_length=20)),
                ('year', models.IntegerField()),
                ('location', models.CharField(choices=[('Paris', 'Paris'), ('Milan', 'Milan'), ('New York', 'New York'), ('London', 'London'), ('Tokyo', 'Tokyo'), ('Other', 'Other')], max_length=50)),
                ('theme', models.CharField(max_length=300)),
                ('show_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.designer')),
            ],
            options={
                'ordering': ['-year', 'season'],
                'unique_together': {('designer', 'season', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TrendItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('color', 'Color'), ('silhouette', 'Silhouette'), ('fabric', 'Fabric/Material'), ('pattern', 'Pattern'), ('accessory', 'Accessory'), ('styling', 'Styling'), ('theme', 'Theme/Concept')], max_length=50)),
                ('popularity_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Rate from 1 (low) to 10 (high)')),
                ('description', models.TextField()),
                ('influence_level', models.CharField(choices=[('niche', 'Niche'), ('emerging', 'Emerging'), ('mainstream', 'Mainstream'), ('iconic', 'Iconic')], default='emerging', max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.collection')),
            ],
            options={
                'ordering': ['-popularity_score', 'trend_name'],
            },
        ),
        migrations.CreateModel(
            name='TrendTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('mentions_count', models.IntegerField(default=0, help_text='Number of collections featuring this trend')),
                ('popularity_rating', models.DecimalField(decimal_places=1, help_text='Average popularity score', max_digits=3)),
                ('trend_status', models.CharField(choices=[('emerging', 'Emerging'), ('rising', 'Rising'), ('peak', 'Peak'), ('declining', 'Declining'), ('archived', 'Archived')], default='emerging', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('trend_name', 'year', 'quarter')},
            },
        ),
    ]
